# Site Settings
title: IRPortfolio
description: IR Portfolio
url: "https://ilyrr.github.io"
baseurl: ""
# baseurl: "/DoomsDayDeviceV3"

# Build Settings
markdown: kramdown
theme: minima # default Jekyll theme

# Exclude these files from the final build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - _Backup/